import { useState } from "react";
import { Send, BookOpen, Sparkles } from "lucide-react";
import api from "../api/client.js";
import Loading from "../components/Loading.jsx";

const SUGGESTED_QUESTIONS = [
  "What TRL level is typically required before a pilot can begin?",
  "What cybersecurity certifications should GovTech vendors have?",
  "How is the achievement percentage for a KPI calculated?",
  "What accessibility standards apply to citizen-facing apps?",
  "When should a pilot be recommended for scale vs iterate vs stop?",
];

export default function RagAssistant() {
  const [query, setQuery] = useState("");
  const [history, setHistory] = useState([]); // { query, answer, sources }
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const ask = async (q) => {
    const question = (q ?? query).trim();
    if (!question) return;
    setLoading(true);
    setError(null);
    try {
      const res = await api.queryRag(question);
      setHistory((h) => [res, ...h]);
      setQuery("");
    } catch (e) {
      setError(
        e.response?.data?.detail ||
          "Could not reach the RAG service. Make sure GROQ_API_KEY is set and ChromaDB has been seeded."
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="page-shell max-w-4xl">
      <div className="page-intro">
        <div>
        <div className="section-label">Knowledge Workspace</div>
        <h1 className="flex items-center gap-2 text-3xl font-black tracking-[-0.045em] text-[#0b2d4a] md:text-4xl">
          <BookOpen className="w-6 h-6 text-maitri-600" />
          Policy & Guidelines Assistant
        </h1>
        <p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">
          Ask questions about procurement, eligibility, cybersecurity, and pilot evaluation guidelines.
          Answers are generated by Groq, grounded in MAITRI's synthetic knowledge base via ChromaDB retrieval.
        </p>
      </div>
      </div>

      <div className="card p-4">
        <div className="flex gap-2">
          <input
            className="input-shell flex-1"
            placeholder="Ask a policy or eligibility question..."
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && ask()}
          />
          <button
            onClick={() => ask()}
            disabled={loading}
            className="btn-primary"
          >
            <Send className="w-4 h-4" /> Ask
          </button>
        </div>
        <div className="flex flex-wrap gap-2 mt-3">
          {SUGGESTED_QUESTIONS.map((q) => (
            <button
              key={q}
              onClick={() => ask(q)}
              className="text-xs bg-slate-100 hover:bg-slate-200 text-slate-600 rounded-full px-3 py-1.5 flex items-center gap-1"
            >
              <Sparkles className="w-3 h-3" /> {q}
            </button>
          ))}
        </div>
      </div>

      {loading && <Loading label="Retrieving context and generating answer..." />}
      {error && <div className="card border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}

      <div className="space-y-4">
        {history.map((item, i) => (
          <div key={i} className="card p-5">
            <div className="text-sm font-semibold text-slate-800 mb-2">{item.query}</div>
            <p className="text-sm text-slate-600 whitespace-pre-wrap">{item.answer}</p>
            {item.sources?.length > 0 && (
              <div className="mt-3 pt-3 border-t border-slate-100">
                <div className="text-xs text-slate-400 mb-1">Sources</div>
                <div className="flex flex-wrap gap-1.5">
                  {item.sources.map((s) => (
                    <span key={s} className="badge bg-slate-100 text-slate-600">{s}</span>
                  ))}
                </div>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
